# Netlify Build Configuration - Ti Presto Genoa Mobile Optimized
[build]
  # Directory to publish - ROOT del repository per deploy automatico
  publish = "."
  
  # Command to run before deploy (opzionale)
  # command = "npm run build"
  
  # Ignore cartelle temporanee e backup nel deploy
  ignore = "deploy_temp/, backup_*, deploy_updated/, *.md, *.ps1, *.zip"

# Headers per sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    # Sicurezza Firebase
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache per asset statici
    Cache-Control = "public, max-age=31536000"

# Headers specifici per HTML (mobile optimization)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Headers per CSS/JS (mobile assets)
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "text/css; charset=utf-8"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/javascript; charset=utf-8"

# Cache ottimizzato per HTML
[[headers]]  
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache per JS/CSS
[[headers]]
  for = "*.js"
  [headers.values] 
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA Redirect - ESSENZIALE per Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom redirects (se necessario)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# Environment variables (per variabili sensibili)
# Configura in Netlify Dashboard → Site settings → Environment variables