# Netlify Build Configuration
[build]
  # Directory to publish (se hai build process)
  publish = "."
  
  # Command to run before deploy (se necessario)
  # command = "npm run build"

# Headers per sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    # Sicurezza Firebase
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache per asset statici
    Cache-Control = "public, max-age=31536000"

# Cache ottimizzato per HTML
[[headers]]  
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache per JS/CSS
[[headers]]
  for = "*.js"
  [headers.values] 
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (se necessario)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# Environment variables (per variabili sensibili)
# Configura in Netlify Dashboard → Site settings → Environment variables